Jagger: com.griddynamics.jagger.engine.e1.collector.CollectThreadsTestListener.provide
init
provide
TestListener com.griddynamics.jagger.engine.e1.collector.CollectThreadsTestListener.provide ()
Method is providing listener to Jagger that will trigger listener methods during test run.
References com.griddynamics.jagger.engine.e1.services.ServicesAware.getMetricService(), com.griddynamics.jagger.engine.e1.collector.test.TestInfo.getThreads(), and com.griddynamics.jagger.engine.e1.services.MetricService.saveValue().
{
         return new TestListener() {
             @Override
             public void onStart(TestInfo testInfo) {}
             @Override
             public void onStop(TestInfo testInfo) {}
             @Override
             public void onRun(TestInfo status) {
                 getMetricService().saveValue(metricId, status.getThreads());
             }
         };
     }